local determinism_evidence = require("sim.determinism_evidence")
local placement = require("sim.placement")
local t = require("spec.support.runner")

t.describe("OMP-1 determinism evidence", function()
    t.it("uses a total order for equal-distance match candidates", function()
        local before = placement.distance_candidate_before
        t.is_true(before({ idx = 9, d = 10 }, { idx = 2, d = 10 }))
        t.is_true(not before({ idx = 2, d = 10 }, { idx = 9, d = 10 }))
        t.is_true(before({ idx = 9, d = 9 }, { idx = 2, d = 10 }))
        t.is_true(not before({ idx = 2, d = 10 }, { idx = 9, d = 9 }))
    end)

    t.it("pins the full fixed-input match on the explicit evidence command", function()
        local result = determinism_evidence.verify()
        t.eq(result.ticks, 7201)
        t.eq(result.boundaries, 7202)
        t.eq(result.score_home, 0)
        t.eq(result.score_away, 1)
        t.eq(result.outcome, "away")
        t.is_true(result.coverage.goal_kickoff)
        t.is_true(result.coverage.tackle)
        t.is_true(result.coverage.aerial)
        t.is_true(result.coverage.keeper)
        t.is_true(result.coverage.full_time)
    end)
end)
