local proof = require("game.webrtc_proof")
local t = require("spec.support.runner")

t.describe("WebRTC proof contract", function()
    t.it("accepts matching handshakes and rejects useful mismatches", function()
        local handshake = assert(proof.new_handshake("host", "build-123"))
        t.is_true(assert(proof.validate_handshake(handshake, 1, "build-123", "host")))

        local _, _, version_code = proof.validate_handshake(handshake, 2, "build-123", "host")
        t.eq(version_code, "unsupported_version")
        local _, _, build_code = proof.validate_handshake(handshake, 1, "build-999", "host")
        t.eq(build_code, "build_mismatch")
        local _, _, role_code = proof.validate_handshake(handshake, 1, "build-123", "guest")
        t.eq(role_code, "role_mismatch")
    end)

    t.it("bounds input history and payload size", function()
        local input = assert(proof.new_input(4, 10, "state", { 4, 5, 6 }))
        t.is_true(assert(proof.validate_input(input)))

        local oversized, _, oversized_code =
            proof.new_input(5, 11, string.rep("x", proof.MAX_INPUT_BYTES + 1), {})
        t.is_true(oversized == nil)
        t.eq(oversized_code, "input_too_large")

        local too_much_history, _, history_code =
            proof.new_input(6, 12, "state", { 1, 2, 3, 4, 5, 6, 7 })
        t.is_true(too_much_history == nil)
        t.eq(history_code, "malformed")
    end)

    t.it("reports gaps, recovery history, reordering, and latency", function()
        local diagnostics = proof.new_diagnostics(0)
        proof.record_sent(diagnostics, 0, 2)
        proof.record_sent(diagnostics, 0.1, 3)
        proof.record_received(diagnostics, 0.2, assert(proof.new_input(1, 1, "a", {})))
        proof.record_received(diagnostics, 0.3, assert(proof.new_input(3, 3, "c", { 2 })))
        proof.record_received(diagnostics, 0.4, assert(proof.new_input(2, 2, "b", {})))
        proof.record_rtt(diagnostics, 20)
        proof.record_rtt(diagnostics, 30)

        local summary = proof.summary(diagnostics, 1)
        t.eq(summary.sent, 2)
        t.eq(summary.received, 3)
        t.eq(summary.unique_ticks, 3)
        t.eq(summary.history_retransmits, 1)
        t.eq(summary.sequence_gaps, 1)
        t.eq(summary.out_of_order, 1)
        t.eq(summary.max_queue_depth, 3)
        t.eq(summary.rtt_p50_ms, 20)
        t.eq(summary.rtt_p95_ms, 30)
        t.eq(summary.jitter_max_ms, 10)
    end)
end)
