local deterministic_math = require("core.deterministic_math")
local match_snapshot = require("sim.match_snapshot")
local t = require("spec.support.runner")

t.describe("core.deterministic_math", function()
    t.it("pins the cross-runtime negative-log regression to exact binary64 bytes", function()
        local ratio = 0.618234602637309
        local result = deterministic_math.negative_log_one_minus(ratio)
        t.eq(match_snapshot.number_bytes(result), "p:0:64622413:83045015")
    end)

    t.it("is finite and monotonic from zero through the caller's upper range", function()
        local zero = deterministic_math.negative_log_one_minus(0)
        local middle = deterministic_math.negative_log_one_minus(0.9)
        local near_limit = deterministic_math.negative_log_one_minus(0.949999999999)
        t.eq(zero, 0)
        t.is_true(zero < middle and middle < near_limit)
        t.is_true(near_limit == near_limit and near_limit < math.huge)
    end)

    t.it("rejects values outside its programmer-error domain", function()
        t.is_true(not pcall(deterministic_math.negative_log_one_minus, -0.000001))
        t.is_true(not pcall(deterministic_math.negative_log_one_minus, 0.95))
        t.is_true(not pcall(deterministic_math.negative_log_one_minus, 1))
    end)
end)
