local t = require("spec.support.runner")
local Vec2 = require("core.vec2")

t.describe("Vec2", function()
    t.it("adds component-wise", function()
        local v = Vec2.new(1, 2):add(Vec2.new(3, 4))
        t.eq(v.x, 4)
        t.eq(v.y, 6)
    end)

    t.it("subtracts component-wise", function()
        local v = Vec2.new(5, 5):sub(Vec2.new(2, 1))
        t.eq(v.x, 3)
        t.eq(v.y, 4)
    end)

    t.it("scales", function()
        local v = Vec2.new(2, -3):scale(2)
        t.eq(v.x, 4)
        t.eq(v.y, -6)
    end)

    t.it("computes length", function()
        t.near(Vec2.new(3, 4):length(), 5)
    end)

    t.it("normalizes to unit length", function()
        t.near(Vec2.new(0, 10):normalized():length(), 1)
        t.eq(Vec2.new(0, 10):normalized().y, 1)
    end)

    t.it("normalizes the zero vector to zero (no NaN)", function()
        local n = Vec2.new(0, 0):normalized()
        t.eq(n.x, 0)
        t.eq(n.y, 0)
    end)

    t.it("measures distance", function()
        t.near(Vec2.new(0, 0):dist(Vec2.new(3, 4)), 5)
    end)
end)
